services:
  nginx:
    mem_limit: 256m
    cpus: 0.50

  web:
    mem_limit: 768m
    cpus: 1.00

  api:
    mem_limit: 768m
    cpus: 1.00

  postgres:
    mem_limit: 1g
    cpus: 1.00

  redis:
    mem_limit: 256m
    cpus: 0.50

  meilisearch:
    mem_limit: 768m
    cpus: 1.00
