services:
  nginx:
    profiles: ["disabled"]

  postgres:
    ports: !reset []

  redis:
    ports: !reset []

  meilisearch:
    ports: !reset []

  web:
    environment:
      NEXT_PUBLIC_API_BASE_URL: /api
    networks:
      default: {}
      proxy:
        aliases: [interpreters-web]

  api:
    environment:
      MEILISEARCH_API_KEY: ${MEILI_MASTER_KEY}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    networks:
      default: {}
      proxy:
        aliases: [interpreters-api]

networks:
  proxy:
    external: true
